import Vue from 'vue'
import { Button, CountDown, Field, Form, NavBar, Tabbar, TabbarItem, Toast, Image as VanImage, Grid, GridItem, Cell, CellGroup, Icon, Tab, Tabs, List, PullRefresh, Popup, Search, Empty, Sticky, Loading, Divider } from 'vant'

Vue.use(Button)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(CountDown)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(VanImage)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Icon)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(Popup)
Vue.use(Search)
Vue.use(Empty)
Vue.use(Sticky)
Vue.use(Loading)
Vue.use(Divider)

Vue.use(Toast)
